#/
# @license Apache-2.0
#
# Copyright (c) 2023 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/

# Workflow name:
name: discussion_comment_bot_response

# Workflow triggers:
on:
  discussion_comment:
    types: [created]

# Global permissions:
permissions:
  # Allow read-only access to the repository contents:
  contents: read

# Workflow jobs:
jobs:
  respond:
    # FIXME: disabled until determination whether enabling this bot is desirable/helpful
    if: false

    # Define a display name:
    name: 'Respond to question'

    # Define the conditions under which the job should run: FIXME: un-comment if and when re-enabled
    # if: github.event.comment.body && startsWith( github.event.comment.body, '/ask ' )

    # Define the type of virtual host machine:
    runs-on: ubuntu-latest

    # Define the sequence of job steps:
    steps:
      # Run the chatbot action:
      - name: 'Run chatbot action'
        # Pin action to full length commit SHA
        uses: stdlib-js/stdlib-chat-bot@6c0643a5a1eb3c782b2df3bfd11e836d2ac7268e # v0.0.1
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.CHATBOT_GITHUB_TOKEN }}
