#/
# @license Apache-2.0
#
# Copyright (c) 2022 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/

# Workflow name:
name: update_contributors

# Workflow triggers:
on:
  schedule:
    # Run the workflow once a day at 2:00 AM UTC:
    - cron: '0 2 * * *'

  # Allow the workflow to be manually run:
  workflow_dispatch:

# Global permissions:
permissions:
  # Allow read-only access to the repository contents:
  contents: read

# Workflow jobs:
jobs:

  # Define a job for updating the contributors list...
  update-contributors:

    # Define a display name:
    name: 'Update contributors'

    # Define the type of virtual host machine:
    runs-on: ubuntu-latest

    # Define the sequence of job steps...
    steps:

      # Checkout the repository:
      - name: 'Checkout repository'
        # Pin action to full length commit SHA
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          # Specify whether to remove untracked files before checking out the repository:
          clean: true

          # Refers to the development branch:
          ref: 'develop'

          # Fetch entire history:
          fetch-depth: 0

          # Specify whether to download Git-LFS files:
          lfs: false
        timeout-minutes: 10

      # Update the contributors list:
      - name: 'Update contributors'
        id: update-contributors
        run: |
          make update-contributors

          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes to commit."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      # Create a pull request:
      - name: 'Create pull request'
        if: steps.update-contributors.outputs.changed == 'true'
        # Pin action to full length commit SHA
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        id: cpr
        with:
          title: 'Update list of contributors'
          body: |
            This PR

            -   updates the list of contributors

          commit-message: 'docs: update list of contributors'
          committer: 'stdlib-bot <noreply@stdlib.io>'
          token: ${{ secrets.PULL_REQUEST_TOKEN }}
          labels: |
            documentation
            automated-pr
          team-reviewers: |
            reviewers
          branch: update-contributors
          delete-branch: true

      # Create a pull request summary:
      - name: 'Create summary'
        run: |
          echo "# :tada: Pull Request created! :tada:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Pull request ${{ steps.cpr.outputs.pull-request-number }} was successfully ${{ steps.cpr.outputs.pull-request-operation }}."
          echo ":link: [${{ steps.cpr.outputs.pull-request-url }}](${{ steps.cpr.outputs.pull-request-url }})." >> $GITHUB_STEP_SUMMARY
          echo "Head SHA: [${{ steps.cpr.outputs.pull-request-head-sha }}](${{ steps.cpr.outputs.pull-request-url }}/commits/${{ steps.cpr.outputs.pull-request-head-sha }})." >> $GITHUB_STEP_SUMMARY
